export const REQUEST_GET_BURGER_INGREDIENTS: "REQUEST_GET_BURGER_INGREDIENTS" = "REQUEST_GET_BURGER_INGREDIENTS";
export const SUCCESS_GET_BURGER_INGREDIENTS: "SUCCESS_GET_BURGER_INGREDIENTS" = "SUCCESS_GET_BURGER_INGREDIENTS";
export const ERROR_GET_BURGER_INGREDIENTS: "ERROR_GET_BURGER_INGREDIENTS" = "ERROR_GET_BURGER_INGREDIENTS";

export const REQUEST_ORDER: "REQUEST_ORDER" = "REQUEST_ORDER";
export const SUCCESS_ORDER: "SUCCESS_ORDER" = "SUCCESS_ORDER";
export const ERROR_ORDER: "ERROR_ORDER" = "ERROR_ORDER";

export const REQUEST_UPDATE_USER_DATA: "REQUEST_UPDATE_USER_DATA" = "REQUEST_UPDATE_USER_DATA";
export const SUCCESS_UPDATE_USER_DATA: "SUCCESS_UPDATE_USER_DATA" = "SUCCESS_UPDATE_USER_DATA";
export const ERROR_UPDATE_USER_DATA: "ERROR_UPDATE_USER_DATA" = "ERROR_UPDATE_USER_DATA";

export const REQUEST_FORGOT_PASSWORD: "REQUEST_FORGOT_PASSWORD" = "REQUEST_FORGOT_PASSWORD";
export const SUCCESS_FORGOT_PASSWORD: "SUCCESS_FORGOT_PASSWORD" = "SUCCESS_FORGOT_PASSWORD";
export const ERROR_FORGOT_PASSWORD: "ERROR_FORGOT_PASSWORD" = "ERROR_FORGOT_PASSWORD";

export const REQUEST_GET_PROFILE_DATA: "REQUEST_GET_PROFILE_DATA" = "REQUEST_GET_PROFILE_DATA";
export const SUCCESS_GET_PROFILE_DATA: "SUCCESS_GET_PROFILE_DATA" = "SUCCESS_GET_PROFILE_DATA";
export const ERROR_GET_PROFILE_DATA: "ERROR_GET_PROFILE_DATA" = "ERROR_GET_PROFILE_DATA";

export const REQUEST_RESET_PASSWORD: "REQUEST_RESET_PASSWORD" = "REQUEST_RESET_PASSWORD";
export const SUCCESS_RESET_PASSWORD: "SUCCESS_RESET_PASSWORD" = "SUCCESS_RESET_PASSWORD";
export const ERROR_RESET_PASSWORD: "ERROR_RESET_PASSWORD" = "ERROR_RESET_PASSWORD";

export const REQUEST_UPDATE_TOKEN: "REQUEST_UPDATE_TOKEN" = "REQUEST_UPDATE_TOKEN";
export const SUCCESS_UPDATE_TOKEN: "SUCCESS_UPDATE_TOKEN" = "SUCCESS_UPDATE_TOKEN";
export const ERROR_UPDATE_TOKEN: "ERROR_UPDATE_TOKEN" = "ERROR_UPDATE_TOKEN";

export const REQUEST_USER_LOGIN: "REQUEST_USER_LOGIN" = "REQUEST_USER_LOGIN";
export const SUCCESS_USER_LOGIN: "SUCCESS_USER_LOGIN" = "SUCCESS_USER_LOGIN";
export const ERROR_USER_LOGIN: "ERROR_USER_LOGIN" = "ERROR_USER_LOGIN";

export const REQUEST_USER_LOGOUT: "REQUEST_USER_LOGOUT" = "REQUEST_USER_LOGOUT";
export const SUCCESS_USER_LOGOUT: "SUCCESS_USER_LOGOUT" = "SUCCESS_USER_LOGOUT";
export const ERROR_USER_LOGOUT: "ERROR_USER_LOGOUT" = "ERROR_USER_LOGOUT";

export const REQUEST_USER_REGISTRATION: "REQUEST_USER_REGISTRATION" = "REQUEST_USER_REGISTRATION";
export const SUCCESS_USER_REGISTRATION: "SUCCESS_USER_REGISTRATION" = "SUCCESS_USER_REGISTRATION";
export const ERROR_USER_REGISTRATION: "ERROR_USER_REGISTRATION" = "ERROR_USER_REGISTRATION";

export const OPEN_WS_CONNECTION_ALL_ORDERS: "OPEN_WS_CONNECTION_ALL_ORDERS" = "OPEN_WS_CONNECTION_ALL_ORDERS";
export const CLOSE_WS_CONNECTION_ALL_ORDERS: "CLOSE_WS_CONNECTION_ALL_ORDERS" = "CLOSE_WS_CONNECTION_ALL_ORDERS";

export const REQUEST_WS_ALL_ORDERS: "REQUEST_WS_ALL_ORDERS" = "REQUEST_WS_ALL_ORDERS";
export const SUCCESS_WS_CONNECTION_ALL_ORDERS: "SUCCESS_WS_CONNECTION__ALL_ORDERS" = "SUCCESS_WS_CONNECTION__ALL_ORDERS";
export const ERROR_WS_CONNECTION_ALL_ORDERS: "ERROR_WS_CONNECTION_ALL_ORDERS" = "ERROR_WS_CONNECTION_ALL_ORDERS";
export const CLOSED_WS_CONNECTION_ALL_ORDERS: "CLOSED_WS_CONNECTION_ALL_ORDERS" = "CLOSED_WS_CONNECTION_ALL_ORDERS";


export const OPEN_WS_CONNECTION_USER_ORDERS: "OPEN_WS_CONNECTION_USER_ORDERS" = "OPEN_WS_CONNECTION_USER_ORDERS";
export const CLOSE_WS_CONNECTION_USER_ORDERS: "CLOSE_WS_CONNECTION_USER_ORDERS" = "CLOSE_WS_CONNECTION_USER_ORDERS";

export const REQUEST_WS_USER_ORDERS: "REQUEST_WS_USER_ORDERS" = "REQUEST_WS_USER_ORDERS";
export const SUCCESS_WS_CONNECTION_USER_ORDERS: "SUCCESS_WS_CONNECTION_USER_ORDERS" = "SUCCESS_WS_CONNECTION_USER_ORDERS";
export const ERROR_WS_CONNECTION_USER_ORDERS: "ERROR_WS_CONNECTION_USER_ORDERS" = "ERROR_WS_CONNECTION_USER_ORDERS";
export const CLOSED_WS_CONNECTION_USER_ORDERS: "CLOSED_WS_CONNECTION_USER_ORDERS" = "CLOSED_WS_CONNECTION_USER_ORDERS";

export const REQUEST_GET_CURRENT_ORDER: "REQUEST_GET_CURRENT_ORDER" = "REQUEST_GET_CURRENT_ORDER";
export const SUCCESS_GET_CURRENT_ORDER: "SUCCESS_GET_CURRENT_ORDER" = "SUCCESS_GET_CURRENT_ORDER";
export const ERROR_GET_CURRENT_ORDER: "ERROR_GET_CURRENT_ORDER" = "ERROR_GET_CURRENT_ORDER";
