export const ADD_BURGER_COMPONENT = 'ADD_BURGER_COMPONENT';
export const REMOVE_BURGER_COMPONENT = 'REMOVE_BURGER_COMPONENT';
export const ADD_BUN = 'ADD_BUN';
export const COUNT_TOTAL_AMOUNT = 'COUNT_TOTAL_AMOUNT';
export const SORT_BURGER_INGREDIENTS = 'SORT_BURGER_INGREDIENTS';

